********************************(21/03/2024 Translation(Supplier field))**************************************(Gobi)
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.CompanyName', 'Company Name', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'اسم الشركة');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Email', 'Email', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'بريد إلكتروني');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Fax', 'Fax', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'فاكس');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Mobile', 'Mobile', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'متحرك');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Status', 'Status', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'حالة');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.GST NO', 'GST NO', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'رقم ضريبة السلع والخدمات'), (NULL, 'mdSupplier.Payment Details', 'Payment Details', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'بيانات الدفع');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Terms', 'Terms', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'شروط');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSuplier.Contact Person', 'Contact Person', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'الشخص الذي يمكن الاتصال به');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Address 1', 'Address 1', NULL, NULL, NULL, NULL, NULL, NULL, '0', '1 العنوان ');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Address 2', 'Address 2', NULL, NULL, NULL, NULL, NULL, NULL, '0', '2 العنوان ');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.State/Zip', 'State/Zip', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'الرمز البريدي الدولة');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Country', 'Country', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'دولة');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Pin Code', 'Pin Code', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'الرمز السري');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Supplier Name', 'Supplier Name', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'اسم المورد');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Website', 'Website', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'موقع إلكتروني');
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`, `arb_value`) VALUES (NULL, 'mdSupplier.Supplier Details', 'Supplier Details', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'تفاصيل المورد');