********************************(22/03/2024 Translation(Purchase-Invoice inserts field))**************************************
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Invoice Code', 'Invoice Code', 'رمز الفاتورة', 'Arabic Invoice Code in Purchase module', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Project Title', 'Project Title', 'عنوان المشروع', 'Project Title arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Client Name', 'Client Name', 'اسم العميل', 'Client Name arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Invoice Date', 'Invoice Date', 'تاريخ الفاتورة', 'Invoice Date arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Amount', 'Amount', 'كمية', 'Amount arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.DueDate', 'Due Date', 'تاريخ الاستحقاق', 'Due Date arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Status', 'Status', 'حالة', 'Status arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Purchase Invoice Code', 'Purchase Invoice Code', 'رمز فاتورة الشراء', 'Purchase Invoice Code arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Project Name', 'Project Name', 'اسم المشروع', 'Project Name arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Supplier Name', 'Supplier Name', 'اسم المورد', 'Supplier Name arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Total Amount', 'Total Amount', 'المبلغ الإجمالي', 'Total Amount arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Mode of Payment', 'Mode of Payment', 'طريقة الدفع', 'Mode of Payment arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Terms and Condition', 'Terms and Condition', 'أحكام وشروط', 'Terms and Condition arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
