********************************(21/03/2024 Translation(Purchase-Invoice inserts field))**************************************
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Invoice Code', 'Invoice Code', 'رمز الفاتورة', 'Arabic Invoice Code in Purchase module', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Project Title', 'Project Title', 'عنوان المشروع', 'Project Title arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Client Name', 'Client Name', 'اسم العميل', 'Client Name arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Invoice Date', 'Invoice Date', 'تاريخ الفاتورة', 'Invoice Date arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Amount', 'Amount', 'كمية', 'Amount arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Due Date', 'Due Date', 'تاريخ الاستحقاق', 'Due Date arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Status', 'Status', 'حالة', 'Status arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Purchase Invoice Code', 'Purchase Invoice Code', 'رمز فاتورة الشراء', 'Purchase Invoice Code arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Project Name', 'Project Name', 'اسم المشروع', 'Project Name arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Supplier Name', 'Supplier Name', 'اسم المورد', 'Supplier Name arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Total Amount', 'Total Amount', 'المبلغ الإجمالي', 'Total Amount arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Mode of Payment', 'Mode of Payment', 'طريقة الدفع', 'Mode of Payment arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Terms and Condition', 'Terms and Condition', 'أحكام وشروط', 'Terms and Condition arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 


********************************(22/03/2024 Translation(Purchase-Invoice inserts field))**************************************
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Title', 'Title', 'عنوان', 'Title arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Unit', 'Unit', 'وحدة', 'Unit arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Ordered Quantity', 'Ordered Quantity', 'الكمية المطلوبة', 'Ordered Quantity arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Unit Price', 'Unit Price', 'سعر الوحدة', 'Unit Price arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Total Cost', 'Total Cost', 'التكلفة الإجمالية', 'Total Cost arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.PO Code', 'PO Code', 'رمز الشراء', 'PO Code arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Quote Date', 'Quote Date', 'تاريخ الاقتباس', 'Quote Date arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 


********************************(22/03/2024 Translation(Purchase-Order inserts field))**************************************
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.PO Code', 'PO Code', 'رمز الشراء', 'PO Code arabic code for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Title', 'Title', 'عنوان', 'Title arabic code for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.PO Value', 'PO Value', 'قيمة أمر الشراء', 'PO Value code for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Status', 'Status', 'حالة', 'Status arabic code for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.PO Date', 'PO Date', 'تاريخ أمر الشراء', 'PO Code arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Supplier Invoice Code', 'Supplier Invoice Code', 'رمز فاتورة المورد', 'Supplier Invoice Code arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Creation Date', 'Creation Date', 'تاريخ الإنشاء', 'Creation Date arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Supplier Name', 'Supplier Name', 'اسم المورد', 'Supplier Name arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.RQ Code', 'RQ Code', 'رمز الاستجابة السريعة', 'RQ Code arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Priority', 'Priority', 'أولوية', 'Priority arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Follow Up Date', 'Follow Up Date', 'متابعة التاريخ', 'Follow Up Date arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
ALTER TABLE `po_product` ADD `item_title_arb` VARCHAR(200) NOT NULL AFTER `item_title`; 
ALTER TABLE `purchase_invoice` ADD `terms_and_condition_arb` VARCHAR(200) NOT NULL AFTER `terms_and_condition`; 
ALTER TABLE `project` ADD `title_arb` VARCHAR(150) NOT NULL AFTER `title`; 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Notes To Supplier', 'Notes To Supplier', 'ملاحظات للمورد', 'Notes To Supplier arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Delivery Terms', 'Delivery Terms', 'شروط التوصيل', 'Delivery Terms arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Payment Terms', 'Payment Terms', 'شروط الدفع', 'Payment Terms arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Payment Status', 'Payment Status', 'حالة السداد', 'Payment Status arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
