********************************(21/03/2024 Translation(Purchase-Invoice inserts field))**************************************
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Invoice Code', 'Invoice Code', 'رمز الفاتورة', 'Arabic Invoice Code in Purchase module', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Project Title', 'Project Title', 'عنوان المشروع', 'Project Title arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Client Name', 'Client Name', 'اسم العميل', 'Client Name arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Invoice Date', 'Invoice Date', 'تاريخ الفاتورة', 'Invoice Date arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Amount', 'Amount', 'كمية', 'Amount arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Due Date', 'Due Date', 'تاريخ الاستحقاق', 'Due Date arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Status', 'Status', 'حالة', 'Status arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Purchase Invoice Code', 'Purchase Invoice Code', 'رمز فاتورة الشراء', 'Purchase Invoice Code arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Project Name', 'Project Name', 'اسم المشروع', 'Project Name arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Supplier Name', 'Supplier Name', 'اسم المورد', 'Supplier Name arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Total Amount', 'Total Amount', 'المبلغ الإجمالي', 'Total Amount arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Mode of Payment', 'Mode of Payment', 'طريقة الدفع', 'Mode of Payment arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Terms and Condition', 'Terms and Condition', 'أحكام وشروط', 'Terms and Condition arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 


********************************(22/03/2024 Translation(Purchase-Invoice inserts field))**************************************
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Title', 'Title', 'عنوان', 'Title arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Unit', 'Unit', 'وحدة', 'Unit arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Ordered Quantity', 'Ordered Quantity', 'الكمية المطلوبة', 'Ordered Quantity arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Unit Price', 'Unit Price', 'سعر الوحدة', 'Unit Price arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Total Cost', 'Total Cost', 'التكلفة الإجمالية', 'Total Cost arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.PO Code', 'PO Code', 'رمز الشراء', 'PO Code arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseInvoice.Quote Date', 'Quote Date', 'تاريخ الاقتباس', 'Quote Date arabic code for Purchase Invoice module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 


********************************(22/03/2024 Translation(Purchase-Order inserts field))**************************************
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.PO Code', 'PO Code', 'رمز الشراء', 'PO Code arabic code for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Title', 'Title', 'عنوان', 'Title arabic code for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.PO Value', 'PO Value', 'قيمة أمر الشراء', 'PO Value code for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Status', 'Status', 'حالة', 'Status arabic code for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.PO Date', 'PO Date', 'تاريخ أمر الشراء', 'PO Code arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Supplier Invoice Code', 'Supplier Invoice Code', 'رمز فاتورة المورد', 'Supplier Invoice Code arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Creation Date', 'Creation Date', 'تاريخ الإنشاء', 'Creation Date arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Supplier Name', 'Supplier Name', 'اسم المورد', 'Supplier Name arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.RQ Code', 'RQ Code', 'رمز الاستجابة السريعة', 'RQ Code arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Priority', 'Priority', 'أولوية', 'Priority arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Follow Up Date', 'Follow Up Date', 'متابعة التاريخ', 'Follow Up Date arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
ALTER TABLE `po_product` ADD `item_title_arb` VARCHAR(200) NOT NULL AFTER `item_title`; 
ALTER TABLE `purchase_invoice` ADD `terms_and_condition_arb` VARCHAR(200) NOT NULL AFTER `terms_and_condition`; 
ALTER TABLE `project` ADD `title_arb` VARCHAR(150) NOT NULL AFTER `title`; 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Notes To Supplier', 'Notes To Supplier', 'ملاحظات للمورد', 'Notes To Supplier arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Delivery Terms', 'Delivery Terms', 'شروط التوصيل', 'Delivery Terms arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Payment Terms', 'Payment Terms', 'شروط الدفع', 'Payment Terms arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Payment Status', 'Payment Status', 'حالة السداد', 'Payment Status arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 

********************************(23/03/2024 Translation(Purchase-Order inserts field))**************************************
ALTER TABLE `purchase_order` ADD `title_arb` VARCHAR(200) NULL DEFAULT NULL AFTER `title`; 
ALTER TABLE `supplier` ADD `company_name_arb` VARCHAR(200) NULL DEFAULT NULL AFTER `company_name`; 
ALTER TABLE `purchase_order` ADD `status_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `status`; 
ALTER TABLE `purchase_order` ADD `notes_arb` VARCHAR(255) NULL DEFAULT NULL AFTER `notes`; 
ALTER TABLE `purchase_order` ADD `delivery_terms_arb` VARCHAR(255) NULL DEFAULT NULL AFTER `delivery_terms`; 
ALTER TABLE `purchase_order` ADD `payment_terms_arb` VARCHAR(254) NULL DEFAULT NULL AFTER `payment_terms`; 
ALTER TABLE `purchase_order` ADD `payment_status_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `payment_status`; 


********************************(25/03/2024 Translation(Purchase-Order inserts field))**************************************
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Item', 'Item', 'غرض', 'Item arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Quantity', 'Quantity', 'كمية', 'Quantity value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Cost Price', 'Cost Price', 'سعر الكلفة', 'Cost Price arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Selling Price', 'Selling Price', 'سعر البيع', 'Selling Price arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.VAT', 'VAT', 'ضريبة القيمة المضافة', 'VAT arabic value for Purchase Order module ', '2023-08-10T16:32:47.036Z', '2024-03-17T15:09:50.890Z', NULL, 'Text', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Product Name', 'Product Name', 'اسم المنتج', 'Product Name arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Product Code', 'Product Code', 'كود المنتج', 'Product Code arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Product Title', 'Product Title', 'عنوان المنتج', 'Product Title arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.GST', 'GST', 'ضريبة السلع والخدمات', 'GST arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Stock', 'Stock', 'مخزون', 'Stock value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Qty', 'Qty', 'الكمية', 'Qtyvalue for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Damaged Qty', 'Damaged Qty', 'الكمية التالفة', 'Damaged Qty value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Added to Stock', 'Added to Stock', 'تمت الإضافة إلى المخزون', 'Added to Stock value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Qty Balance', 'Qty Balance', 'رصيد الكمية', 'Qty Balance value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Total Amount', 'Total Amount', 'المبلغ الإجمالي', 'Total Amount Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Actual Total Amount', 'Actual Total Amount', 'المبلغ الإجمالي الفعلي', 'Actual Total Amount Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
ALTER TABLE `po_product` ADD `status_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `status`; 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Date', 'Date', 'تاريخ', 'Date Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Price', 'Price', 'سعر', 'Price Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
ALTER TABLE `comment` ADD `comments_arb` VARCHAR(255) NULL DEFAULT NULL AFTER `comments`; 


********************************(26/03/2024 Translation(Job Information inserts field))**************************************
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.EMP Code', 'EMP Code', 'رمز الموظف', 'EMP Code Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Full Name', 'Full Name', 'الاسم الكامل', 'Full Name Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.FIN No', 'FIN No', 'رقم النهاية', 'Fin No Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.NRIC No', 'NRIC No', 'رقم نريك', 'Nric No Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.DOB', 'DOB', 'تاريخ الميلاد', 'DOB Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Basic Pay', 'Basic Pay', 'الدفع الأساسي', 'Basic Pay Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Pass Type', 'Pass Type', 'نوع المرور', 'Pass Type Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.id', 'id', 'بطاقة تعريف', 'id Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Employee Name', 'Employee Name', 'اسم الموظف', 'Employee Name Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL);
ALTER TABLE `employee` ADD `first_name_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `first_name`;  
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Employment Start/Commencement Date ', 'Employment Start/Commencement Date ', 'تاريخ بدء/بدء التوظيف', 'Employment Start/Commencement Date Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Duties & Responsibility', 'Duties & Responsibility', 'الواجبات والمسؤولية', 'Duties & Responsibility Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Duration of Employment(only for employees on fixed term contract)', 'Duration of Employment(only for employees on fixed term contract)', 'مدة التوظيف (فقط للموظفين بعقود محددة المدة)', 'Duration Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Place of Work(if different from companys registered address)', 'Place of Work(if different from companys registered address)', 'مكان العمل (إذا كان مختلفًا عن العنوان المسجل للشركة)', 'Address Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
ALTER TABLE `job_information` ADD `duty_responsibility_arb` VARCHAR(100) NULL DEFAULT NULL AFTER `duty_responsibility`; 
ALTER TABLE `job_information` ADD `place_of_work_arb` VARCHAR(155) NULL DEFAULT NULL AFTER `place_of_work`; 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Details of Working Hours', 'Details of Working Hours', 'تفاصيل ساعات العمل', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Rest day per Week', 'Rest day per Week', 'يوم راحة في الأسبوع', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Paid Annual Leave per year', 'Paid Annual Leave per year', 'إجازة سنوية مدفوعة الأجر سنويا', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Paid Outpatient Sick Leave per year', 'Paid Outpatient Sick Leave per year', 'إجازة مرضية للمرضى الخارجيين مدفوعة الأجر سنويًا', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Paid Hospitalisation Leave per year', 'Paid Hospitalisation Leave per year', 'إجازة استشفاء مدفوعة الأجر سنويًا', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Paid medical examination fee', ' Paid medical examination fee', 'دفع رسوم الفحص الطبي', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Other types of leave', 'Other types of leave', 'أنواع أخرى من الإجازات', '', '', '', NULL, '', '0', NULL);
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Other Medical Benefits', 'Other Medical Benefits', 'مريض', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Under Probation', 'Under Probation', 'تحت الاختبار', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Employment Type', 'Employment Type', 'نوع الوظيفة', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Designation', 'Designation', 'نوع الوظيفة', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Department', 'Department', 'قسم', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Joined/Arrival Date ', 'Joined/Arrival Date ', 'تاريخ الانضمام/الوصول', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Status', 'Status', 'حالة', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Salary Period', 'Salary Period', 'فترة الراتب', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Date(s) of Salary Payment', 'Date(s) of Salary Payment', 'تاريخ (تواريخ) دفع الراتب', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Date(s) of Overtime Payment (if different)', 'Date(s) of Overtime Payment (if different)', 'تاريخ (تواريخ) دفع العمل الإضافي (إذا كان مختلفًا)', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Working Calendar(No of Days/Week)(KET)', 'Working Calendar(No of Days/Week)(KET)', 'تقويم العمل (عدد الأيام/الأسبوع) (KET)', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Overtime Applicable', 'Overtime Applicable', 'ينطبق العمل الإضافي', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Overtime Pay Rate/ Hour', 'Overtime Pay Rate/ Hour', 'معدل دفع العمل الإضافي / الساعة', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Transport', 'Transport', 'ينقل', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Entertainment', 'Entertainment', 'ترفيه', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Food', 'Food', 'طعام', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Shift Allowance', 'Shift Allowance', 'بدل التحول', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Others', 'Others', 'آحرون', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Housing', 'Housing', 'السكن', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Transportation', 'Transportation', 'مواصلات', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Levy', 'Levy', 'الجبايه', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.CPF Applicable', ' CPF Applicable', 'ينطبق CPF', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Pay CDAC', 'Pay CDAC', 'دفع CDAC\r\n', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Income Tax No', 'Income Tax No', 'رقم ضريبة الدخل', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Income Tax Amount', 'Income Tax Amount', 'مبلغ ضريبة الدخل', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.CPF No', 'CPF No', 'رقم CPF', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Mode of Payment', 'Mode of Payment', 'طريقة الدفع', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Account No', 'Account No', 'رقم الحساب', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Bank Name', 'Bank Name', 'اسم البنك', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Bank Code', 'Bank Code', 'رمز بنكي', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Branch Code', 'Branch Code', 'رمز الفرع', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Notice Period for Termination', 'Notice Period for Termination', 'فترة الإشعار بالإنهاء', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Date of Resignation Notice', 'Date of Resignation Notice', 'تاريخ إشعار الاستقالة', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Termination/Cessation Date', 'Termination/Cessation Date', 'تاريخ الإنهاء/التوقف', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Departure Date', 'Departure Date', 'تاريخ المغادرة', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdJobInformation.Reason for Termination', 'Reason for Termination', 'سبب الإنهاء', '', '', '', NULL, '', '0', NULL);
ALTER TABLE `job_information` ADD `work_hour_details_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `work_hour_details`; 
ALTER TABLE `job_information` ADD `notice_period_for_termination_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `notice_period_for_termination`; 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Employee Name', 'Employee Name', 'اسم الموظف', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Payslip Print', 'Payslip Print', 'طباعة قسيمة الدفع', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Month', 'Month', 'شهر', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Year', 'Year', 'سنة', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.OT', 'OT', 'بعد ذلك', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.CPF(Employer)', 'CPF(Employer)', 'CPF (صاحب العمل)', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.CPF(Employee)', 'CPF(Employee)', 'CPF (الموظف)', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Allowance', 'Allowance', 'مخصص', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Deductions', 'Deductions', 'الخصومات', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Net Pay', 'Net Pay', 'صافي الأجر', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Status', 'Status', 'حالة', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.ID', 'ID', 'بطاقة تعريف', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.ANNUAL LEAVE AS PER MOM', 'ANNUAL LEAVE AS PER MOM', 'الإجازة السنوية حسب رغبة الأم', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.1st year: 7 days', '1st year: 7 days', 'السنة الأولى: 7 أيام', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.4th year: 10 days', '4th year: 10 days', 'السنة الرابعة: 10 أيام', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.7th year: 13 days', '7th year: 13 days', 'السنة السابعة: 13 يومًا', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.2nd year: 8 days', '2nd year: 8 days', 'السنة الثانية: 8 أيام', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.5th year: 11 days', '5th year: 11 days', 'السنة الخامسة: 11 يومًا', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.8th year thereafter: 14 days', '8th year thereafter: 14 days', 'السنة الثامنة بعد ذلك: 14 يومًا', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.3rd year: 9 days', '3rd year: 9 days', 'السنة الثالثة: 9 أيام', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.6th year: 12 days', '6th year: 12 days', 'السنة السادسة: 12 يومًا', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.SICK LEAVE AS PER MOM', 'SICK LEAVE AS PER MOM', 'إجازة مرضية حسب رغبة الأم', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.After 3 months: 5 days', 'After 3 months: 5 days', 'بعد 3 أشهر: 5 أيام', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.After 4 months: 8 days', 'After 4 months: 8 days', 'بعد 4 أشهر: 8 أيام', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.After 5 months: 11 days', 'After 5 months: 11 days', 'بعد 5 أشهر: 11 يومًا', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.6 months and thereafter: 14 days', '6 months and thereafter: 14 days', '6 أشهر وما بعدها: 14 يومًا', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Total No of leave taken this year', 'Total No of leave taken this year', 'إجمالي عدد الإجازات المتخذة هذا العام', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Total No of leave taken this Month', 'Total No of leave taken this Month', 'إجمالي عدد الإجازات المتخذة هذا الشهر', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Annual leave', 'Annual leave', 'الإجازة السنوية', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Sick leave', 'Sick leave', 'أجازة مرضية', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Hospitalization leave', 'Hospitalization leave', 'إجازة الاستشفاء', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Absent leave', 'Absent leave', 'إجازة غائبة', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Start Date', 'Start Date', 'تاريخ البدء', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.End Date', 'End Date', 'تاريخ الانتهاء', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Working Days in Month', 'Working Days in Month', 'أيام العمل في الشهر', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Actual worked days in month', 'Actual worked days in month', 'أيام العمل الفعلية في الشهر', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Mode Of Payment', 'Mode Of Payment', 'طريقة الدفع', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Employee Name(DOB)', 'Employee Name(DOB)', 'اسم الموظف (DOB)', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Generated Date', 'Generated Date', 'تاريخ الإنشاء', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Basic Pay', 'Basic Pay', 'الدفع الأساسي', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Gross Pay', 'Gross Pay', 'إجمالي الراتب', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Overtime Pay Rate/ Hour', 'Overtime Pay Rate/ Hour', 'معدل دفع العمل الإضافي / الساعة', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.OT Hrs', 'OT Hrs', 'من ساعة', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Overtime Amount', 'Overtime Amount', 'مبلغ العمل الإضافي', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Transport', 'Transport', 'ينقل', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Entertainment', 'Entertainment', 'ترفيه', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Food', 'Food', 'طعام', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Shift Allowance', 'Shift Allowance', 'بدل التحول', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Others', 'Others', 'آحرون', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Other Additional Payment', 'Other Additional Payment', 'دفع إضافي آخر', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Reimbursement', 'Reimbursement', 'السداد', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Director Fees', 'Director Fees', 'رسوم المدير', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Advance / Loan', 'Advance / Loan', 'سلفة / قرض', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Income Tax', 'Income Tax', 'ضريبة الدخل', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Housing', 'Housing', 'السكن', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Transportation', 'Transportation', 'مواصلات', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Pay EUCF', 'Pay EUCF', 'دفع EUCF', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Total Deductions', 'Total Deductions', 'إجمالي الخصومات', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.View loan breakup', 'View loan breakup', 'عرض تفكك القرض', '', '', '', NULL, '', '0', NULL); 
ALTER TABLE `purchase_invoice_items` ADD `item_title_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `item_title`; 

********************************(28/03/2024 project task )**********************************

ALTER TABLE `project_task` CHANGE `job_order_id` `project_job_id` INT(11) NULL DEFAULT NULL; 

********************************(29/03/2024 translation)**********************************

INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.Grand Total', 'Grand Total', 'المجموع الإجمالي', 'Grand Total arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.View History', 'View History', 'عرض السجل', 'View History Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPurchaseOrder.History', 'History', 'تاريخ', 'History Arabic value for Purchase Order module ', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Pay CDAC', 'Pay CDAC', 'دفع CDAC', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Pay SINDA', 'Pay SINDA', 'ادفع سيندا', '', '', '', NULL, '', '0', NULL); 
INSERT INTO `translation` (`translation_id`, `key_text`, `value`, `arb_value`, `chi_value`, `creation_date`, `modification_date`, `group_name`, `is_html_text`, `show_to_user`, `flag`) VALUES (NULL, 'mdPayrollManagement.Pay MBMF', 'Pay MBMF', 'دفع إم بي إم إف', '', '', '', NULL, '', '0', NULL); 

********************************(01/04/2024 Purchase Invoice-translation)**********************************
ALTER TABLE `purchase_invoice_items` ADD `unit_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `unit`; 
ALTER TABLE `purchase_invoice_items` ADD `ordered_quantity_arb` INT(11) NULL DEFAULT NULL AFTER `ordered_quantity`; 
ALTER TABLE `purchase_invoice_items` ADD `cost_price_arb` INT(11) NULL DEFAULT NULL AFTER `cost_price`; 
ALTER TABLE `purchase_invoice_items` ADD `total_cost_arb` INT(11) NULL DEFAULT NULL AFTER `total_cost`; 
ALTER TABLE `po_product` ADD `cost_price_arb` VARCHAR(50) NULL DEFAULT NULL AFTER `cost_price`; 
ALTER TABLE `po_product` ADD `selling_price_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `selling_price`; 
ALTER TABLE `po_product` ADD `gst_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `gst`; 
ALTER TABLE `po_product` ADD `qty_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `qty`; 
ALTER TABLE `po_product` ADD `damage_qty_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `damage_qty`; 
ALTER TABLE `po_product` ADD `qty_delivered_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `qty_delivered`; 


********************************(02/04/2024 Purchase Invoice-translation)**********************************

ALTER TABLE `job_information` ADD `rest_day_per_week_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `rest_day_per_week`; 
ALTER TABLE `job_information` ADD `paid_annual_leave_per_year_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `paid_annual_leave_per_year`; 
ALTER TABLE `job_information` ADD `paid_outpatient_sick_leave_per_year_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `paid_outpatient_sick_leave_per_year`; 
ALTER TABLE `job_information` ADD `other_type_of_leave_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `other_type_of_leave`; 
ALTER TABLE `job_information` ADD `other_medical_benefits_arb` VARCHAR(200) NULL DEFAULT NULL AFTER `other_medical_benefits`; 
ALTER TABLE `job_information` ADD `paid_hospitalisation_leave_per_year_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `paid_hospitalisation_leave_per_year`;
ALTER TABLE `job_information` ADD `length_of_probation_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `length_of_probation`; 
ALTER TABLE `job_information` ADD `probation_start_date_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `probation_start_date`; 
ALTER TABLE `job_information` ADD `probation_end_date_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `probation_end_date`; 
 ALTER TABLE `purchase_invoice` ADD `purchase_invoice_code_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `purchase_invoice_code`; 
 ALTER TABLE `purchase_invoice` ADD `invoice_amount_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `invoice_amount`; 
 ALTER TABLE `employee` ADD `passport_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `passport`; 
 ALTER TABLE `employee` ADD `fin_no_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `fin_no`; 
 ALTER TABLE `employee` ADD `nric_no_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `nric_no`; 
 ALTER TABLE `job_information` ADD `basic_pay_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `basic_pay`; 
 ALTER TABLE `employee` ADD `citizen_arb` VARCHAR(55) NULL DEFAULT NULL AFTER `citizen`; 
